---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-operator
  labels:
    name: istio-operator
  name: istio-operator
spec:
  ports:
  - port: 443
    name: webhook
    targetPort: 8443
  - name: http-metrics
    port: 8383
    targetPort: 8383
  selector:
    name: istio-operator
...
